### ISSUE TITLE
Need pairs-year data

### ISSUE THREAD

**Issue by ghost** [EA31337/FX-MT-VM-Docker#1]
The following pairs of data and tags are required.
I need your support.

USDJPY-2018-DS
GBPUSD-2018-DS
USDCHF-2018-DS
AUDUSD-2018-DS
USDCAD-2018-DS

**Comment by kenorb** [comment]
Done. The requested tags has been generated. Please test. If you need more, please let me know.
https://hub.docker.com/r/ea31337/ea-tester/tags

**Comment by ghost** [comment]
Thank you so much for your quick response.
I will test with the pair you have just added. If I need more pairs, I will issue a ticket!
